const data = [
  {
    name: "BetasoI-C Oral 1l",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Calcimin - P Oral 50ml",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Calcimin - P Oral 1l",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Calcimin - P Oral 5l",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Cholin-750 Oral 1l",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Intrasan pH Oral 1l",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Intrasan pH Oral 5l",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Introchick Oral 50ml",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Introchick Oral 100ml",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Introchick Oral 500ml",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Introchick Oral 1l",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Introvit A + WS 100g",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Introvit A + WS 1kg",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Introvit-C WS 100g",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Introvit-C WS 1kg",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Introvit-ES-100 Oral 50ml",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Introvit-ES-100 Oral 100ml",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Introvit-ES-100 Oral 1l",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Introvit-ES-100 Oral 5l",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Introvit -ES-200 WS 1kg",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Methiosol-880 Oral 1l",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Stressol Oral 50ml",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Stressol Oral 100ml",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Stressol Oral 500ml",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Stressol Oral 1l",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Stressol Oral 5l",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Intertrim 480 oral 10ml",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Intertrim 480 oral 100ml",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Intertrim 480 oral 1l",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Macrotyl 250 oral 10ml",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Macrotyl 250 oral 240ml",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Macrotyl 250 oral 960ml",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "piperin 30g",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "piperin 100g",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "piperin 1kg",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "biocilline 200ws 10g",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "biocilline 200ws 1kg",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "biocilline 500ws 100g",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "biocilline 500ws 1kg",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Doxy -200 WS 1kg",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Doxy -500 WS 1kg",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Leva-200 WS 100g",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Leva-200 WS 100g",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Leva-200 WS 1kg",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Interflox Oral 10ml",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Interflox Oral 100ml",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Interflox Oral 1l",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Macrolan WS 100g",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Macrolan WS 1kg",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Amprocox WS 100g",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Amprocox WS 1kg",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Aquapure-1000",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Banixin -50",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Biocillin-150 LA ",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Butasal-100",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Glucortin-20 ",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Imochem 120",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Intermectin ",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Intertrim ",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Intrafer -100 B 12",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Introvit",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Introvit E -Selen",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Ketosol-100",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Limoxin-200 LA ",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Limoxin-50",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Oxytocin-20",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Vitol-140 ",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Xyla",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Limoxin Spray",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "AlbenoI 100 Oral",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Calmasol -440",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Febnol 100 Oral 15ml",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Febnol 100 Oral 1l",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Intracal P Drench ",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Interzan Gold Oral 40ml",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Interzan Gold Oral 100ml",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Interzan Gold Oral 500ml",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Interzan Gold Oral 1l",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Topicure Pet",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Reliflam Spray",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Fresh Me Up",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Fresh Me Up Bloom",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Nomoticks Body Spray",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Junior Bites",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Digestive Bites",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Smart Bites",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Pet Shampoo",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Alovera Pet Shampoo",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Tick & Fleas Pet Shampoo",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Lassie (NH)",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Lassie (AR)",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Lassie (CB)",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Remedium",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Tick-Out Shampoo",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Tick-Out Soap",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Sebo-Rid Shampoo",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Super Stress",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Alivio",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Ostogen-VP",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "hematopet",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "livetonick vp",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Mexidin",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Kalcevit",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Semavit",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Semavit Plus",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Biomix Plus",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Kittycat",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Prominol (1BA)",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Prominol (5BA)",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Prominol (10BA)",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Prominol (25BA)",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Prominol (5BU)",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Soya been meal",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Maze ",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Fish meel",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "DCP",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Dl methinion",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Thriyonine",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Enerzyme",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Toxinbind",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Asidifire",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Lysine",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
  {
    name: "Premix",
    id: Math.random() * 1000,
    selected: false,
    qty: 0,
  },
]

export default data
